SpatialFun/Controllers/AttractionController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MvcApplication2.Models;

namespace MvcApplication2.Controllers
{
    public class AttractionController : Controller
    {
        private AttractionContext db = new AttractionContext();

        //
        // GET: /Attraction/

        public ActionResult Index()
        {
            return View(db.TouristAttractions.ToList());
        }

        //
        // GET: /Attraction/Details/5

        public ActionResult Details(int id = 0)
        {
            TouristAttraction touristattraction = db.TouristAttractions.Find(id);
            if (touristattraction == null)
            {
                return HttpNotFound();
            }
            return View(touristattraction);
        }

        //
        // GET: /Attraction/Create

        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /Attraction/Create

        [HttpPost]
        public ActionResult Create(TouristAttraction touristattraction)
        {
            if (ModelState.IsValid)
            {
                db.TouristAttractions.Add(touristattraction);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(touristattraction);
        }

        //
        // GET: /Attraction/Edit/5

        public ActionResult Edit(int id = 0)
        {
            TouristAttraction touristattraction = db.TouristAttractions.Find(id);
            if (touristattraction == null)
            {
                return HttpNotFound();
            }
            return View(touristattraction);
        }

        //
        // POST: /Attraction/Edit/5

        [HttpPost]
        public ActionResult Edit(TouristAttraction touristattraction)
        {
            if (ModelState.IsValid)
            {
                db.Entry(touristattraction).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(touristattraction);
        }

        //
        // GET: /Attraction/Delete/5

        public ActionResult Delete(int id = 0)
        {
            TouristAttraction touristattraction = db.TouristAttractions.Find(id);
            if (touristattraction == null)
            {
                return HttpNotFound();
            }
            return View(touristattraction);
        }

        //
        // POST: /Attraction/Delete/5

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            TouristAttraction touristattraction = db.TouristAttractions.Find(id);
            db.TouristAttractions.Remove(touristattraction);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

SpatialFun/Views/Attraction/Create.cshtml
@model MvcApplication2.Models.TouristAttraction

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>

@using (Html.BeginForm("Create", "Attraction", FormMethod.Post, new { id = "CreateAttraction" }))
{
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>TouristAttraction</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.Name)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Name)
            @Html.ValidationMessageFor(model => model.Name)
        </div>
        <div class="editor-label">
            @Html.LabelFor(model => model.Location)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Location)        
        </div>
        <p>
            <input type="submit" value="Create" />
        </p>
    </fieldset>
}

<div>    
      @Html.RouteLink("Back to List","Default",new {Controller="Attraction", action="Index"})
</div>

@section Scripts {  
    @Scripts.Render("~/bundles/jqueryval") 
    <script type="text/javascript" src="~/Scripts/EFSpatialGoogleMaps.js"/></script>
}

SpatialFun/Views/Attraction/Delete.cshtml
@model MvcApplication2.Models.TouristAttraction

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<fieldset>
    <legend>TouristAttraction</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Name)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Name)
    </div>
</fieldset>
@using (Html.BeginForm()) {
    <p>
        <input type="submit" value="Delete" /> |
        @Html.RouteLink("Back to List","Default",new {Controller="Attraction", action="Index"})
    </p>
}
@section Scripts {    
    <script type="text/javascript" src="~/Scripts/EFSpatialGoogleMaps.js"/></script>
}


SpatialFun/Views/Attraction/Details.cshtml
@model MvcApplication2.Models.TouristAttraction

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<fieldset>
    <legend>TouristAttraction</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Name)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Name)
    </div>

    <div class="display-label">
        @Html.DisplayNameFor(model => model.Location)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Location)        
    </div>
</fieldset>
<p>
    @Html.RouteLink("Edit", "Default",new {Controller="Attraction", action="Edit",id=Model.TouristAttractionId})    
    @Html.RouteLink("Back to List","Default",new {Controller="Attraction", action="Index"})
</p>

@section Scripts {    
    <script type="text/javascript" src="~/Scripts/EFSpatialGoogleMaps.js"/></script>
}


SpatialFun/Views/Attraction/Edit.cshtml
@model MvcApplication2.Models.TouristAttraction

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>

@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>TouristAttraction</legend>

        @Html.HiddenFor(model => model.TouristAttractionId)

        <div class="editor-label">
            @Html.LabelFor(model => model.Name)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Name)
            @Html.ValidationMessageFor(model => model.Name)
        </div>
          <div class="editor-label">
            @Html.LabelFor(model => model.Location)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Location)        
        </div>
        <p>
            <input type="submit" value="Save" />
        </p>
    </fieldset>
}

<div>
    
    @Html.RouteLink("Back to List","Default",new {Controller="Attraction", action="Index"})
</div>

@section Scripts {    
   @* We are sharing the script manager with the one on Site.master so we don't need these. *@
    @* Scripts.Render("~/bundles/jqueryval") *@    
    @*<script type="text/javascript" src="~/Scripts/EFSpatialGoogleMaps.js"/></script>*@
}
}

SpatialFun/Views/Attraction/Index.cshtml
@model IEnumerable<MvcApplication2.Models.TouristAttraction>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Index</h2>

<p>
    @Html.RouteLink("Create New","Default",new {Controller="Attraction", action="Create"})
</p>
<table>
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.RouteLink("Edit", "Default",new {Controller="Attraction", action="Edit",id=item.TouristAttractionId}) |
            @Html.RouteLink("Details", "Default",new {Controller="Attraction", action="Details",id=item.TouristAttractionId})|
            @Html.RouteLink("Delete", "Default",new {Controller="Attraction", action="Delete",id=item.TouristAttractionId})
        </td>
    </tr>
}

</table>